#!/bin/bash

# Get script dir
DEST_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#echo "Creating folder structure in /run/shm"
SHM_DIR=/run/shm
mkdir -p $SHM_DIR/rec
mkdir -p $SHM_DIR/hooks
mkdir -p $SHM_DIR/state
mkdir -p $DEST_DIR/archive

#echo "Creating symbolic links to /run/shm dir"
ln -sfn $DEST_DIR/archive $SHM_DIR/rec/archive
ln -sfn $SHM_DIR/rec $DEST_DIR/rec
ln -sfn $SHM_DIR/hooks $DEST_DIR/hooks
ln -sfn $SHM_DIR/state $DEST_DIR/state

